estudos/curso_udemy/django/blog/urls.py
from django.contrib import admin 
from django.urls import path
from . import views

app_name = 'blog'

# Django urls
# https://docs.djangoproject.com/en/5.2/topics/http/urls/

urlpatterns = [
    path('<int:post_id>/', views.post, name='post'), # Sempre colocar a url mais específica primeiro, para evitar problemas (quanto mais coisa na url)
    path('', views.blog, name='home'),
    path('exemplo/', views.exemplo, name='exemplo'),
]

estudos/curso_udemy/django/home/urls.py
from django.contrib import admin 
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

estudos/curso_udemy/django/project/urls.py
from django.contrib import admin 
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

estudos/curso_udemy/django/blog/models.py
from django.db import models

# Create your models here.

estudos/curso_udemy/django/home/models.py
from django.db import models

# Create your models here.

estudos/curso_udemy/django/blog/views.py
from django.shortcuts import render
from blog.data import posts
from django.http import HttpRequest, Http404
from typing import Any


# HTTP Request <-> HTTP Response
# Django funciona por MVT (Model View Template), variação de MVC (Model View Controller)

# Create your views here.

def blog(request):
    print("blog") # Pode fazer oque quiser dentro da função
    
    context = {
        # 'text': 'Olá blog',
        'title': 'Blog',
        'posts': posts,
    }
    
    return render(request, 'blog/index.html', context)

def post(request: HttpRequest, post_id: int):
    found_post: dict[str, Any] = None
    
    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break
    
    if found_post is None:
        raise Http404('Post não existe.')

    context = {
        'title': found_post['title'],
        'post': found_post,
    }
    
    return render(request, 'blog/post.html', context)

def exemplo(request):
    
    context = {
        'text': 'Olá exemplo do blog',
        'title': 'Exemplo',
    }
    
    return render(request, 'blog/exemplo.html', context)

estudos/curso_udemy/django/home/views.py
from django.shortcuts import render

# HTTP Request <-> HTTP Response
# Django funciona por MVT (Model View Template), variação de MVC (Model View Controller)

# Create your views here.

def home(request):
    print("home") # Pode fazer oque quiser dentro da função
    
    context = {
        'text': 'Olá home',
        'title': 'Home',
    }
    
    return render(request, 'home/index.html', context)

def exemplo(request):
    print("global") # Pode fazer oque quiser dentro da função
    
    context = {
        'text': 'Olá exemplo do home',
        'title': 'Exemplo home',
    }
    
    return render(request, 'home/exemplo.html', context)

estudos/curso_udemy/django/blog/templates/blog/exemplo.html
{% extends "global/base.html" %}

{% block texto %}
{{ text }}
{% endblock texto %}

estudos/curso_udemy/django/blog/templates/blog/index.html
{% extends "global/base.html" %}

{% if text %}
    {% block texto %} {{ text }} {% endblock texto %}
{% endif %}

{% block posts %}
    {% for post in posts%}
        {% include "global/partials/postblock.html" %}
    {% endfor %}
{% endblock posts %}

estudos/curso_udemy/django/blog/templates/blog/post.html
{% extends "global/base.html" %}

{% if text %}
    {% block texto %} {{ text }} {% endblock texto %}
{% endif %}

{% block posts %}
    <article class="post single-post">
        <span>
            <h1 class="post__title">
                <a href="{% url "blog:post" post.id %}" class="post-anchor">
                    {{ post.title }}
                </a>
            </h1>
        </span>

        <div class="post__content">
            {{ post.body }}
        </div>
    </article>
{% endblock posts %}

estudos/curso_udemy/django/home/templates/home/exemplo.html
{% extends 'global/base.html' %}

{% block texto %}
{{ text }}
{% endblock texto %}

estudos/curso_udemy/django/home/templates/home/index.html
{% extends 'global/base.html' %}

{% block texto %} 
{{ text }}
{% endblock texto %}